Translate Adopting Concurrent Mode
reactjs/id.reactjs.org pull request #195
Opened 2020-09-18 04:38 UTC by padulkemid

This is my first translation, any advice and suggestions are greatly appreciated! 🍻   
If I do some mistake, please let me know! Thank you very much 👍

2020-11-23 08:40 UTC, padulkemid commented
I left this like a month and I forgot to mention T_T I'm sorry, can I have a review please ? hehehe @resir014

2020-12-13 03:48 UTC, resir014 requested changes
LGTM! Mostly just layout issues, please look at them.

2020-12-13 03:48 UTC, resir014 commented on content/docs/concurrent-mode-adoption.md
> +title: Menggunakan Concurrent Mode (Experimental)
```suggestion
title: Mengadopsi Concurrent Mode (Experimental)
```

I think "mengadopsi" is also a valid translation.

2020-12-13 03:48 UTC, resir014 commented on content/docs/concurrent-mode-adoption.md
> +ketika ada suatu masalah. Anda telah diperingatkan!
Please keep all paragraphs in a single line. Don't wrap them.

This will cause merge conflicts when we pull in new content from the English site.

2020-12-29 21:46 UTC, padulkemid commented
I might be fixed all the issues related to paragraphs, can I get a review ? 😄   @resir014

2020-12-31 06:33 UTC, resir014 approved these changes

2020-12-31 06:33 UTC, merged